angular.module('app.test').controller('RegistrationCtrl', function (sampleService, $log) {
    var vm = this;
    vm.processUnits = [
            {
                "processunitcode": "R",
                "processunitdescription": "Raw Material",
                "createdby": "Admin",
                "createddate": "2023-03-14T18:27:43",
                "updatedby": "",
                "updateddate": null,
                "processunitid": 5
            },
            {
                "processunitcode": "O",
                "processunitdescription": "Others",
                "createdby": "Admin",
                "createddate": "2023-03-14T18:27:43",
                "updatedby": "",
                "updateddate": null,
                "processunitid": 7
            },
            {
                "processunitcode": "G",
                "processunitdescription": "Germane",
                "createdby": "Admin",
                "createddate": "2023-03-14T18:27:43",
                "updatedby": "",
                "updateddate": null,
                "processunitid": 2
            },
            {
                "processunitcode": "D",
                "processunitdescription": "Diborane",
                "createdby": "Admin",
                "createddate": "2023-03-14T18:27:43",
                "updatedby": "",
                "updateddate": null,
                "processunitid": 1
            },
            {
                "processunitcode": "Y",
                "processunitdescription": "Germane - R&D and Pilot",
                "createdby": "Admin",
                "createddate": "2023-03-14T18:27:43",
                "updatedby": "",
                "updateddate": null,
                "processunitid": 3
            },
            {
                "processunitcode": "X",
                "processunitdescription": "Diborane - R&D and Pilot",
                "createdby": "Admin",
                "createddate": "2023-03-14T18:27:43",
                "updatedby": "",
                "updateddate": null,
                "processunitid": 8
            }
        ];

    vm.sampleTypes = [
        {
            "sampletypecode": "FG",
            "sampletypedescription": "Finish Good",
            "submission": "Manual",
            "remark": null,
            "createddate": "2023-03-10T22:17:09",
            "createdby": "Admin",
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 1
        },
        {
            "sampletypecode": "INS",
            "sampletypedescription": "Inspection",
            "submission": "Manual",
            "remark": null,
            "createddate": "2023-12-11T07:22:03",
            "createdby": "Admin",
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 14
        },
        {
            "sampletypecode": "CHEMICALS",
            "sampletypedescription": "Chemicals Stock",
            "submission": "Scheduled and Manual",
            "remark": null,
            "createddate": "2024-06-25T15:03:03",
            "createdby": "MOHD HUSSIN BIN IDRIS",
            "modifieddate": "2024-07-08T15:36:20",
            "modifiedby": "MOHD HUSSIN BIN IDRIS",
            "order": null,
            "sampletypeid": 15
        },
        {
            "sampletypecode": "ISOTANK",
            "sampletypedescription": "Isotank",
            "submission": "Scheduled and Manual",
            "remark": null,
            "createddate": "2024-09-08T10:13:18",
            "createdby": "MOHD HUSSIN BIN IDRIS",
            "modifieddate": "2024-09-08T10:31:37",
            "modifiedby": "MOHD HUSSIN BIN IDRIS",
            "order": null,
            "sampletypeid": 16
        },
        {
            "sampletypecode": "SR",
            "sampletypedescription": "Shift Report",
            "submission": "Scheduled and Manual",
            "remark": null,
            "createddate": "2024-10-27T17:59:12",
            "createdby": "MOHD HUSSIN BIN IDRIS",
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 17
        },
        {
            "sampletypecode": "BLD",
            "sampletypedescription": "Product Blending",
            "submission": "Manual",
            "remark": null,
            "createddate": "2024-11-04T15:07:15",
            "createdby": "MOHD HUSSIN BIN IDRIS",
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 18
        },
        {
            "sampletypecode": "FOAMING",
            "sampletypedescription": "Foaming Polyol",
            "submission": "Scheduled and Manual",
            "remark": "R&D Polyol",
            "createddate": "2024-11-21T11:52:39",
            "createdby": "MOHD HUSSIN BIN IDRIS",
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 19
        },
        {
            "sampletypecode": "DRUM",
            "sampletypedescription": "Drumming",
            "submission": "Scheduled and Manual",
            "remark": null,
            "createddate": "2024-12-21T06:56:17",
            "createdby": "MOHD HUSSIN BIN IDRIS",
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 20
        },
        {
            "sampletypecode": "EXT_LAB",
            "sampletypedescription": "External Laboratory",
            "submission": "Manual",
            "remark": null,
            "createddate": "2025-01-13T10:24:19",
            "createdby": "MOHD HUSSIN BIN IDRIS",
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 22
        },
        {
            "sampletypecode": "WSH",
            "sampletypedescription": "Washing",
            "submission": "Scheduled and Manual",
            "remark": null,
            "createddate": "2025-05-13T15:10:35",
            "createdby": "MOHD ZULHAIRI BIN JAMALUDDIN",
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 23
        },
        {
            "sampletypecode": "LSR",
            "sampletypedescription": "Laboratory Service Request",
            "submission": "Manual",
            "remark": "LSR",
            "createddate": "2025-06-25T16:48:08",
            "createdby": "MOHD HUSSIN BIN IDRIS",
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 24
        },
        {
            "sampletypecode": "QCC",
            "sampletypedescription": "QC Check",
            "submission": "Manual",
            "remark": null,
            "createddate": "2025-08-20T12:12:42",
            "createdby": "MOHD HUSSIN BIN IDRIS",
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 25
        },
        {
            "sampletypecode": "REF",
            "sampletypedescription": "Reference",
            "submission": "Manual",
            "remark": null,
            "createddate": null,
            "createdby": null,
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 13
        },
        {
            "sampletypecode": "STD",
            "sampletypedescription": "Standard",
            "submission": "Manual",
            "remark": null,
            "createddate": null,
            "createdby": null,
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 12
        },
        {
            "sampletypecode": "RND",
            "sampletypedescription": "R&D",
            "submission": "Manual",
            "remark": null,
            "createddate": null,
            "createdby": null,
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 8
        },
        {
            "sampletypecode": "PLT",
            "sampletypedescription": "Pilot",
            "submission": "Manual",
            "remark": null,
            "createddate": null,
            "createdby": null,
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 9
        },
        {
            "sampletypecode": "OTR",
            "sampletypedescription": "Others",
            "submission": "Manual",
            "remark": null,
            "createddate": null,
            "createdby": null,
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 11
        },
        {
            "sampletypecode": "PCA",
            "sampletypedescription": "Pre-COA",
            "submission": "Manual",
            "remark": null,
            "createddate": null,
            "createdby": null,
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 10
        },
        {
            "sampletypecode": "REQ",
            "sampletypedescription": "Request",
            "submission": "Manual",
            "remark": null,
            "createddate": null,
            "createdby": null,
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 4
        },
        {
            "sampletypecode": "SFG",
            "sampletypedescription": "Semi Finish Good",
            "submission": "Scheduled and Manual",
            "remark": null,
            "createddate": null,
            "createdby": null,
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 3
        },
        {
            "sampletypecode": "IPC",
            "sampletypedescription": "In Process",
            "submission": "Manual",
            "remark": null,
            "createddate": null,
            "createdby": null,
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 5
        },
        {
            "sampletypecode": "UTL",
            "sampletypedescription": "Utilities",
            "submission": "Scheduled and Manual",
            "remark": null,
            "createddate": null,
            "createdby": null,
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 6
        },
        {
            "sampletypecode": "RM",
            "sampletypedescription": "Raw Material",
            "submission": "Manual",
            "remark": null,
            "createddate": null,
            "createdby": null,
            "modifieddate": null,
            "modifiedby": null,
            "order": null,
            "sampletypeid": 2
        }
    ];

    vm.materials = [
            {
                "productid": 713,
                "productcode": "Hydrogen",
                "productdescription": null,
                "supplier": "Air Product",
                "purity": "5N5",
                "processunitid": 5,
                "processunitcode": "R",
                "processunitdescription": "Raw Material",
                "sampletypeid": 2,
                "sampletypecode": "RM",
                "sampletypedescription": "Raw Material",
                "createddate": "2026-07-30T06:17:24",
                "createdby": "admin",
                "modifieddate": "2026-07-30T06:35:02",
                "modifiedby": "admin",
                "expiryperiod": null,
                "prdctsampltypprcssuntid": null,
                "hazardinfolist": [],
                "frontendmaterialsampletypeprocessunit": null
            },
            {
                "productid": 715,
                "productcode": "Hydrogen",
                "productdescription": null,
                "supplier": "Hsing Mien",
                "purity": "7N",
                "processunitid": 5,
                "processunitcode": "R",
                "processunitdescription": "Raw Material",
                "sampletypeid": 2,
                "sampletypecode": "RM",
                "sampletypedescription": "Raw Material",
                "createddate": "2026-07-30T06:17:33",
                "createdby": "admin",
                "modifieddate": "2026-07-30T06:35:02",
                "modifiedby": "admin",
                "expiryperiod": null,
                "prdctsampltypprcssuntid": null,
                "hazardinfolist": [],
                "frontendmaterialsampletypeprocessunit": null
            },
            {
                "productid": 716,
                "productcode": "Hydrogen",
                "productdescription": null,
                "supplier": "Micron (10%)",
                "purity": "6N",
                "processunitid": 5,
                "processunitcode": "R",
                "processunitdescription": "Raw Material",
                "sampletypeid": 2,
                "sampletypecode": "RM",
                "sampletypedescription": "Raw Material",
                "createddate": "2026-07-30T06:17:39",
                "createdby": "admin",
                "modifieddate": "2026-07-30T06:35:02",
                "modifiedby": "admin",
                "expiryperiod": null,
                "prdctsampltypprcssuntid": null,
                "hazardinfolist": [],
                "frontendmaterialsampletypeprocessunit": null
            },
            {
                "productid": 717,
                "productcode": "Hydrogen",
                "productdescription": null,
                "supplier": "SMC (30%)",
                "purity": "6N",
                "processunitid": 5,
                "processunitcode": "R",
                "processunitdescription": "Raw Material",
                "sampletypeid": 2,
                "sampletypecode": "RM",
                "sampletypedescription": "Raw Material",
                "createddate": "2026-07-30T06:17:44",
                "createdby": "admin",
                "modifieddate": "2026-07-30T06:35:02",
                "modifiedby": "admin",
                "expiryperiod": null,
                "prdctsampltypprcssuntid": null,
                "hazardinfolist": [],
                "frontendmaterialsampletypeprocessunit": null
            },
            {
                "productid": 718,
                "productcode": "Hydrogen",
                "productdescription": null,
                "supplier": "SMC (0.1%)",
                "purity": "6N",
                "processunitid": 5,
                "processunitcode": "R",
                "processunitdescription": "Raw Material",
                "sampletypeid": 2,
                "sampletypecode": "RM",
                "sampletypedescription": "Raw Material",
                "createddate": "2026-07-30T06:17:52",
                "createdby": "admin",
                "modifieddate": "2026-07-30T06:35:02",
                "modifiedby": "admin",
                "expiryperiod": null,
                "prdctsampltypprcssuntid": null,
                "hazardinfolist": [],
                "frontendmaterialsampletypeprocessunit": null
            },
            {
                "productid": 719,
                "productcode": "Nitrogen",
                "productdescription": null,
                "supplier": "Air Liquide",
                "purity": null,
                "processunitid": 5,
                "processunitcode": "R",
                "processunitdescription": "Raw Material",
                "sampletypeid": 2,
                "sampletypecode": "RM",
                "sampletypedescription": "Raw Material",
                "createddate": "2026-07-30T15:05:32",
                "createdby": "admin",
                "modifieddate": null,
                "modifiedby": null,
                "expiryperiod": null,
                "prdctsampltypprcssuntid": null,
                "hazardinfolist": [],
                "frontendmaterialsampletypeprocessunit": null
            },
            {
                "productid": 721,
                "productcode": "Nitrogen",
                "productdescription": null,
                "supplier": "Ledeen",
                "purity": null,
                "processunitid": 5,
                "processunitcode": "R",
                "processunitdescription": "Raw Material",
                "sampletypeid": 2,
                "sampletypecode": "RM",
                "sampletypedescription": "Raw Material",
                "createddate": "2026-07-30T15:05:43",
                "createdby": "admin",
                "modifieddate": null,
                "modifiedby": null,
                "expiryperiod": null,
                "prdctsampltypprcssuntid": null,
                "hazardinfolist": [],
                "frontendmaterialsampletypeprocessunit": null
            },
            {
                "productid": 722,
                "productcode": "Nitrogen",
                "productdescription": null,
                "supplier": "Micron (5%)",
                "purity": "6N",
                "processunitid": 5,
                "processunitcode": "R",
                "processunitdescription": "Raw Material",
                "sampletypeid": 2,
                "sampletypecode": "RM",
                "sampletypedescription": "Raw Material",
                "createddate": "2026-07-30T15:02:13",
                "createdby": "admin",
                "modifieddate": null,
                "modifiedby": null,
                "expiryperiod": null,
                "prdctsampltypprcssuntid": null,
                "hazardinfolist": [],
                "frontendmaterialsampletypeprocessunit": null
            },
            {
                "productid": 723,
                "productcode": "Nitrogen",
                "productdescription": null,
                "supplier": "ST Micro (0.8%)",
                "purity": "5N5",
                "processunitid": 5,
                "processunitcode": "R",
                "processunitdescription": "Raw Material",
                "sampletypeid": 2,
                "sampletypecode": "RM",
                "sampletypedescription": "Raw Material",
                "createddate": "2026-07-30T15:02:40",
                "createdby": "admin",
                "modifieddate": null,
                "modifiedby": null,
                "expiryperiod": null,
                "prdctsampltypprcssuntid": null,
                "hazardinfolist": [],
                "frontendmaterialsampletypeprocessunit": null
            }
        ];

    vm.register = function() {
        sampleService.list().then(function (samples) {
            vm.countries = [{key: "MY", value: "Malaysia"}];
            $log.log('samples updated via register', vm.countries);
        });
    };
});